// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS6GXR89QnwN1z3Dvziunfbt9ekmhOqSo',
    appId: '1:957678705948:web:a41135f4d08792961d6ed9',
    messagingSenderId: '957678705948',
    projectId: 'beejuday-notifications',
    authDomain: 'beejuday-notifications.firebaseapp.com',
    storageBucket: 'beejuday-notifications.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK_6mqPlQpkv8G3YxuSq3E0mBUATrUe90',
    appId: '1:957678705948:android:fb8cdfce2fb10f3d1d6ed9',
    messagingSenderId: '957678705948',
    projectId: 'beejuday-notifications',
    storageBucket: 'beejuday-notifications.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa4siRoXKxyZX4-zHeoh5tTAC3YLElB7Y',
    appId: '1:957678705948:ios:ed0d23402a9f867d1d6ed9',
    messagingSenderId: '957678705948',
    projectId: 'beejuday-notifications',
    storageBucket: 'beejuday-notifications.firebasestorage.app',
    iosBundleId: 'com.example.beejuDay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa4siRoXKxyZX4-zHeoh5tTAC3YLElB7Y',
    appId: '1:957678705948:ios:ed0d23402a9f867d1d6ed9',
    messagingSenderId: '957678705948',
    projectId: 'beejuday-notifications',
    storageBucket: 'beejuday-notifications.firebasestorage.app',
    iosBundleId: 'com.example.beejuDay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS6GXR89QnwN1z3Dvziunfbt9ekmhOqSo',
    appId: '1:957678705948:web:4c6417b5b5110ce81d6ed9',
    messagingSenderId: '957678705948',
    projectId: 'beejuday-notifications',
    authDomain: 'beejuday-notifications.firebaseapp.com',
    storageBucket: 'beejuday-notifications.firebasestorage.app',
  );
}
